---
- name: Get List of Published Posts
  ansible.builtin.command: >
    wp post list --post_type=post --field=ID
    --path=/home/semaphore/{{ site.linux_user }}
    --allow-root
  register: post_ids
  changed_when: false

- name: Fetch Current Post Content
  ansible.builtin.command: >
    wp post get {{ item }} --field=post_content
    --path=/home/semaphore/{{ site.linux_user }}
    --allow-root
  register: old_content
  changed_when: false
  loop: "{{ post_ids.stdout_lines }}"
  when: post_ids.stdout_lines | length > 0

- name: Generate AI Replacement Text
  ansible.builtin.uri:
    url: "https://e34f-186-7-97-57.ngrok-free.app/api/generate"
    method: POST
    body_format: json
    body:
      model: "llama3"
      prompt: |
        Rewrite the following blog post in a friendly, concise style.
        Keep headings as Markdown (##) and end with a call to action.

        ORIGINAL:
        {{ old_content.results[loop_index].stdout }}
      stream: false
    status_code: 200
    timeout: 120
  register: ollama_reply
  loop: "{{ post_ids.stdout_lines }}"
  loop_control:
    index_var: loop_index
  when: post_ids.stdout_lines | length > 0

- name: Update Posts with Generated Content
  ansible.builtin.command: >
    wp post update {{ item.0 }}
    --post_content="{{ item.1.json.response | quote }}"
    --path=/home/semaphore/{{ site.linux_user }}
    --allow-root
  loop: "{{ post_ids.stdout_lines | zip(ollama_reply.results) | list }}"
  register: update_results
  changed_when: update_results.rc == 0
  when: post_ids.stdout_lines | length > 0

- name: Log Post Updates
  ansible.builtin.debug:
    msg: "Post {{ item }} on {{ site.domain }} rewritten by Ollama"
  loop: "{{ post_ids.stdout_lines }}"
  when: post_ids.stdout_lines | length > 0 