---
- name: Get Home Page ID
  ansible.builtin.set_fact:
    content_ids:
      stdout_lines: ["11"]

- name: Fetch Current Content
  ansible.builtin.command: >
    wp post get {{ item }} --field=post_content
    --path=/home/semaphore/{{ site.linux_user }}
    --allow-root
  register: old_content
  changed_when: false
  loop: "{{ content_ids.stdout_lines }}"
  when: content_ids.stdout_lines | length > 0

# - name: Generate AI Replacement Text
#   ansible.builtin.uri:
#     url: "https://16ce-186-7-97-57.ngrok-free.app/api/generate"
#     method: POST
#     body_format: json
#     body:
#       model: "llama3.2"
#       prompt: |
#         You are a technology expert writer. Rewrite the following content in a professional, 
#         engaging style that focuses on technical accuracy and practical implementation. 
        
#         Guidelines:
#         1. Maintain all technical details and code snippets exactly as they appear
#         2. Explain complex concepts in clear, accessible language
#         3. Add relevant technical context where appropriate
#         4. Keep all HTML/markdown formatting
#         5. Include practical examples or use cases
#         6. End with a technical call-to-action or next steps
        
#         ORIGINAL:
#         {{ old_content.results[loop_index].stdout }}
#       stream: false
#     status_code: 200
#     timeout: 120
#   register: ollama_reply
#   loop: "{{ content_ids.stdout_lines }}"
#   loop_control:
#     index_var: loop_index
#   when: content_ids.stdout_lines | length > 0

- name: Generate new text with Ollama
  uri:
    url: "https://2eed-38-52-162-179.ngrok-free.app/api/generate"
    method: POST
    body_format: json
    body:
      model: astra-page-writer:latest
      prompt: |
        Rewrite the following WordPress *page* in a friendly, concise style.
        Keep every <img …> tag exactly unchanged.

        ORIGINAL:
        {{ old_content.results[loop_index].stdout }}
      stream: false
    status_code: 200
    timeout: 300
    validate_certs: false
  register: ollama_reply
  retries: 3
  delay: 10
  until: ollama_reply is success
  loop: "{{ content_ids.stdout_lines }}"
  loop_control:
    index_var: loop_index
    pause: 5
  when: content_ids.stdout_lines | length > 0

- name: Debug Ollama Response
  ansible.builtin.debug:
    msg: "Response length: {{ ollama_reply.results[0].json.response | length }}"

- name: Create temporary content file
  ansible.builtin.copy:
    content: "{{ ollama_reply.results[0].json.response }}"
    dest: "/tmp/wp-content-{{ content_ids.stdout_lines[0] }}.html"
    mode: '0644'
  when: content_ids.stdout_lines | length > 0

- name: Get Current Page Template
  ansible.builtin.command: >
    wp post meta get {{ content_ids.stdout_lines[0] }} _wp_page_template
    --path=/home/semaphore/{{ site.linux_user }}
    --allow-root
  register: page_template
  when: content_ids.stdout_lines | length > 0

- name: Update Content with Generated Text
  ansible.builtin.command: >
    wp post update {{ content_ids.stdout_lines[0] }} 
    --path=/home/semaphore/{{ site.linux_user }}
    --allow-root
    --post_content="$(cat /tmp/wp-content-{{ content_ids.stdout_lines[0] }}.html)"
    --meta_input='{"_wp_page_template":"{{ page_template.stdout | default("default") }}"}'
  register: update_results
  changed_when: update_results.rc == 0
  when: content_ids.stdout_lines | length > 0
  vars:
    ansible_command_timeout: 30
  environment:
    WP_CLI_DEBUG: "1"
    WP_CLI_LOG_LEVEL: "debug"

- name: Clean up temporary files
  ansible.builtin.file:
    path: "/tmp/wp-content-{{ content_ids.stdout_lines[0] }}.html"
    state: absent
  when: content_ids.stdout_lines | length > 0

- name: Debug Update Results
  ansible.builtin.debug:
    msg: "Update status: {{ update_results.rc }} - Output: {{ update_results.stdout_lines | default([]) }} - Error: {{ update_results.stderr_lines | default([]) }}"
  when: content_ids.stdout_lines | length > 0

- name: Log Content Updates
  ansible.builtin.debug:
    msg: "Home page on {{ site.domain }} rewritten by Ollama"
  when: content_ids.stdout_lines | length > 0