---
- name: Cleanup All WordPress Domains, Databases, and Users
  hosts: wordpress
  become: true

  vars:
    wordpress_sites:
      - domain: example1.com
        host: example1.com
        db_name: wp_example1
        db_user: wpuser1
        linux_user: user1
        site_dir: sites1

  tasks:

    - name: Disable Apache sites
      loop: "{{ wordpress_sites }}"
      loop_control:
        loop_var: site
      command: "a2dissite {{ site.domain }}"
      ignore_errors: yes

    - name: Remove Apache vhost file
      loop: "{{ wordpress_sites }}"
      loop_control:
        loop_var: site
      file:
        path: "/etc/apache2/sites-available/{{ site.domain }}.conf"
        state: absent
      ignore_errors: yes

    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Drop MySQL databases
      loop: "{{ wordpress_sites }}"
      loop_control:
        loop_var: site
      mysql_db:
        name: "{{ site.db_name }}"
        state: absent

    - name: Remove MySQL users
      loop: "{{ wordpress_sites }}"
      loop_control:
        loop_var: site
      mysql_user:
        name: "{{ site.db_user }}"
        host: "localhost"
        state: absent

    - name: Remove Document Roots (e.g. user's home or site folder)
      loop: "{{ wordpress_sites }}"
      loop_control:
        loop_var: site
      file:
        path: "/home/{{ site.linux_user }}"
        state: absent
      ignore_errors: yes

    - name: Remove Linux users
      loop: "{{ wordpress_sites }}"
      loop_control:
        loop_var: site
      user:
        name: "{{ site.linux_user }}"
        state: absent
        remove: yes
        force: yes
      ignore_errors: yes
