---
- name: Robust Multi-Domain WordPress Setup
  hosts: wordpress
  become: true

  vars:
    wordpress_sites:
      - domain: example5.com
        host: 10.92.82.53
        port: 8086
        db_name: wp_example6
        db_user: wpuser6
        db_pass: SecurePass6!
        wp_admin_user: admin6
        wp_admin_pass: AdminPass6!
        wp_admin_email: admin6@example.com
        site_dir: sites6

  tasks:
    - name: Install Dependencies (Apache, PHP, MariaDB, WP-CLI)
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - libapache2-mod-php
          - mariadb-server
          - mariadb-client
          - python3-mysqldb
          - unzip
          - curl
        update_cache: yes
        state: present

    - name: Ensure Apache modules enabled
      apache2_module:
        name: "{{ item }}"
        state: present
      loop:
        - rewrite
        - proxy
        - proxy_http
        - ssl
        - headers

    - name: Start and Enable MariaDB
      service:
        name: mariadb
        state: started
        enabled: true

    - name: Configure firewall to allow each site port
      ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: tcp
      loop: "{{ wordpress_sites }}"

    - name: Add custom Listen ports to /etc/apache2/ports.conf
      lineinfile:
        path: /etc/apache2/ports.conf
        line: "Listen {{ item.port }}"
        insertafter: EOF
        state: present
      loop: "{{ wordpress_sites }}"

    - name: Deploy each WordPress site
      include_tasks: wordpress_site_setup.yml
      loop: "{{ wordpress_sites }}"
      loop_control:
        loop_var: site

    - name: Restart Apache after all changes
      service:
        name: apache2
        state: restarted
        enabled: true
