---
- name: Robust Multi-Domain WordPress Setup
  hosts: localhost
  become: true
  # gather_timeout: 10
  vars:
    wordpress_sites:
      - domain: "{{ DOMAIN }}"
        host: "{{ HOST }}"
        db_name: "{{ DB_NAME }}"
        db_user: "{{ DB_USER }}"
        db_pass: "{{ DB_PASS }}"
        access_db_user: "{{ ACCESS_DB_USER }}"
        access_db_pass: "{{ ACCESS_DB_PASS }}"
        wp_admin_user: "{{  WP_ADMIN_USER }}"
        wp_admin_pass: "{{ WP_ADMIN_PASS }}"
        wp_admin_email: "{{ WP_ADMIN_EMAIL }}"
        website_name: "{{ WEBSITE_NAME }}"
        linux_user: "{{ LINUX_USER }}"

      # - domain: example1.com
      #   host: example1.com
      #   db_name: wp_example1
      #   db_user: wpuser1
      #   db_pass: SecurePass1!
      #   wp_admin_user: admin1
      #   wp_admin_pass: AdminPass1!
      #   wp_admin_email: admin1@example.com
      #   website_name: sites1
      #   linux_user: user1

  tasks:
    - name: Debug all variables
      debug:
        var: item
      loop: "{{ wordpress_sites }}"

    # - name: Install Dependencies (Apache, PHP, MariaDB, WP-CLI)
    #   apt:
    #     name:
    #       - apache2
    #       - php
    #       - php-mysql
    #       - libapache2-mod-php
    #       - mariadb-server
    #       - mariadb-client
    #       - python3-mysqldb
    #       - unzip
    #       - curl
    #     update_cache: yes
    #     state: present

    - name: Ensure Apache modules enabled
      apache2_module:
        name: "{{ item }}"
        state: present
      loop:
        - rewrite
        - proxy
        - proxy_http
        - ssl
        - headers

    - name: Start and Enable MariaDB
      service:
        name: mariadb
        state: started
        enabled: true

    # - name: Configure firewall to allow each site port
    #   ufw:
    #     rule: allow
    #     port: "{{ item.port }}"
    #     proto: tcp
    #   loop: "{{ wordpress_sites }}"

    # - name: Add custom Listen ports to /etc/apache2/ports.conf
    #   lineinfile:
    #     path: /etc/apache2/ports.conf
    #     line: "Listen {{ item.port }}"
    #     insertafter: EOF
    #     state: present
    #   loop: "{{ wordpress_sites }}"

    - name: Deploy each WordPress site
      include_tasks: wordpress_site_setup.yml
      loop: "{{ wordpress_sites }}"
      loop_control:
        loop_var: site

    - name: Restart Apache after all changes
      service:
        name: apache2
        state: reloaded
        enabled: true

    - name: Install WP-CLI
      get_url:
        url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        dest: /usr/local/bin/wp
        mode: "0755"

    - name: Install theme via WP-CLI
      command: >
        wp theme install https://downloads.wordpress.org/theme/oceanwp.3.4.3.zip
        --path=/home/semaphore/{{ wordpress_sites.linux_user }}
        --allow-root
      args:
        chdir: /usr/local/bin
      ignore_errors: true

    - name: Activate theme via WP-CLI
      command: >
        wp theme activate oceanwp
        --path=/home/semaphore/{{ wordpress_sites.linux_user }}
        --allow-root
      args:
        chdir: /usr/local/bin
      ignore_errors: true

 