- hosts: localhost
  vars:
    ansible_connection: local
    ansible_remote_tmp: "/tmp/.ansible-2323453664"
  tasks:
    - name: Who am I?
      command: whoami
      register: whoami_result

    - debug:
        msg: "Running as {{ whoami_result.stdout }}"