- hosts: localhost
  become: true
  gather_facts: false
  vars:
    ansible_connection: local
  tasks:
    - name: Who am I?
      command: whoami
      register: whoami_result

    - debug:
        msg: "Running as {{ whoami_result.stdout }}"