- name: Create site directory /var/www/{{ site.site_dir }}
  file:
    path: "/var/www/{{ site.site_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"

- name: Create database "{{ site.db_name }}"
  mysql_db:
    name: "{{ site.db_name }}"
    state: present

- name: Create DB user "{{ site.db_user }}"
  mysql_user:
    name: "{{ site.db_user }}"
    password: "{{ site.db_pass }}"
    priv: "{{ site.db_name }}.*:ALL"
    state: present

- name: Unarchive WordPress directly into /var/www/{{ site.site_dir }}
  unarchive:
    src: "https://wordpress.org/latest.zip"
    dest: "/var/www/{{ site.site_dir }}"
    remote_src: yes

- name: Move extracted contents up and remove folder
  shell: mv /var/www/{{ site.site_dir }}/wordpress/* /var/www/{{ site.site_dir }} && rmdir /var/www/{{ site.site_dir }}/wordpress
  args:
    executable: /bin/bash
  ignore_errors: true

- name: Configure wp-config.php
  template:
    src: wp-config.php.j2
    dest: "/var/www/{{ site.site_dir }}/wp-config.php"
    owner: www-data
    group: www-data
    mode: "0644"

- name: Configure Apache VirtualHost for {{ site.domain }}
  template:
    src: "vhost.j2"
    dest: "/etc/apache2/sites-available/{{ site.domain }}.conf"

- name: a2ensite {{ site.domain }}
  command: a2ensite {{ site.domain }}

- name: Restart Apache after all changes
  service:
    name: apache2
    state: restarted
    enabled: true

- name: run the WordPress installation
  uri:
    url: "http://{{ site.host }}:{{ site.port }}/wp-admin/install.php?step=2"
    method: POST
    body: "weblog_title={{ site.site_dir }}&user_name={{ site.wp_admin_user }}&admin_password={{ site.wp_admin_pass }}&admin_password2={{ site.wp_admin_pass }}&admin_email={{ site.wp_admin_email }}"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    status_code: 200
  register: wordpress_install
  ignore_errors: yes

- name: show the output of the WordPress installation
  debug:
    var: wordpress_install.content
  ignore_errors: yes

