# - name: Set permissions for semaphore working directory
#   file:
#     path: "/home/semaphore/{{ site.linux_user }}"
#     state: directory
#     recurse: yes
#     owner: semaphore
#     group: semaphore
#     mode: '0755'

- name: (Optional) Create Linux user "{{ site.linux_user }}"
  user:
    name: "{{ site.linux_user }}"
    home: "/home/semaphore/{{ site.linux_user }}"
    shell: /bin/bash
    groups: "www-data"
  ignore_errors: true

- name: Create site directory /home/semaphore/{{ site.linux_user }}
  file:
    path: "/home/semaphore/{{ site.linux_user }}"
    state: directory
    owner: semaphore
    group: semaphore
    mode: "0755"

- name: Create database "{{ site.db_name }}"
  mysql_db:
    name: "{{ site.db_name }}"
    state: present
    login_user: "semaphore"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create DB user "{{ site.db_user }}"
  mysql_user:
    name: "{{ site.db_user }}"
    password: "{{ site.db_pass }}"
    priv: "{{ site.db_name }}.*:ALL"
    state: present
    host: localhost
    login_unix_socket: /var/run/mysqld/mysqld.sock

# - name: Create MySQL user for each domain
#   mysql_user:
#     name: "{{ item.db_user }}"
#     password: "{{ item.db_pass }}"
#     priv: "{{ item.db_name }}.*:ALL"
#     host: localhost
#     state: present
#     login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Unarchive WordPress directly into /home/semaphore/{{ site.linux_user }}
  unarchive:
    src: "https://wordpress.org/latest.zip"
    dest: "/home/semaphore/{{ site.linux_user }}"
    remote_src: true

- name: Move extracted contents up and remove folder
  shell: mv /home/semaphore/{{ site.linux_user }}/wordpress/* /home/semaphore/{{ site.linux_user }} && rmdir /home/semaphore/{{ site.linux_user }}/wordpress
  args:
    executable: /bin/bash
  ignore_errors: true

- name: Configure wp-config.php
  template:
    src: wp-config.php.j2
    dest: "/home/semaphore/{{ site.linux_user }}/wp-config.php"
    owner: semaphore
    group: semaphore
    mode: "0644"

- name: Configure Apache VirtualHost for {{ site.domain }}
  template:
    src: "vhost.j2"
    dest: "/etc/apache2/sites-available/{{ site.domain }}.conf"

- name: a2ensite {{ site.domain }}
  command: a2ensite {{ site.domain }}

- name: Restart Apache after all changes
  service:
    name: apache2
    state: restarted
    enabled: true

- name: run the WordPress installation
  uri:
    url: "http://{{ site.host }}/wp-admin/install.php?step=2"
    method: POST
    body: >
      weblog_title={{ site.website_name }}
      &user_name={{ site.wp_admin_user }}
      &admin_password={{ site.wp_admin_pass }}
      &admin_password2={{ site.wp_admin_pass }}
      &admin_email={{ site.wp_admin_email }}
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    status_code: 200
  register: wordpress_install
  ignore_errors: true

- name: show the output of the WordPress installation
  debug:
    var: wordpress_install.content
  ignore_errors: true
