# - name: (Optional) Create Linux user "{{ site.linux_user }}"
#   user:
#     name: "{{ site.linux_user }}"
#     home: "/home/semaphore/{{ site.linux_user }}"
#     shell: /bin/bash
#     groups: "www-data"
#   ignore_errors: true

- name: Create site directory /home/semaphore/{{ site.linux_user }}
  file:
    path: "/home/semaphore/{{ site.linux_user }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"

- name: Create database "{{ site.db_name }}"
  mysql_db:
    name: "{{ site.db_name }}"
    state: present
    login_user: "{{ site.access_db_user }}"
    login_password: "{{ site.access_db_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create DB user "{{ site.db_user }}"
  mysql_user:
    name: "{{ site.db_user }}"
    password: "{{ site.db_pass }}"
    priv: "{{ site.db_name }}.*:ALL"
    login_user: "{{ site.access_db_user }}"
    login_password: "{{ site.access_db_pass }}"
    state: present
    host: localhost
    login_unix_socket: /var/run/mysqld/mysqld.sock


- name: Unarchive WordPress directly into /home/semaphore/{{ site.linux_user }}
  unarchive:
    src: "https://wordpress.org/latest.zip"
    dest: "/home/semaphore/{{ site.linux_user }}"
    remote_src: true

- name: Move extracted contents up and remove folder
  shell:
    cmd: >
      mv /home/semaphore/{{ site.linux_user }}/wordpress/* /home/semaphore/{{ site.linux_user }}
      && rmdir /home/semaphore/{{ site.linux_user }}/wordpress
  args:
    executable: /bin/bash
  ignore_errors: true

- name: Configure wp-config.php
  template:
    src: wp-config.php.j2
    dest: "/home/semaphore/{{ site.linux_user }}/wp-config.php"
    owner: www-data
    group: www-data
    mode: "0755"


- name: Configure Apache VirtualHost for {{ site.domain }}
  become: true
  template:
    src: "vhost.j2"
    dest: "/etc/apache2/sites-available/{{ site.domain }}.conf"
    owner: root
    group: root
    mode: "0755"

- name: Enable Apache sites
  command: "a2ensite {{ site.domain }}"
  args:
    creates: "/etc/apache2/sites-enabled/{{ site.domain }}.conf"

- name: Fix ownership to www-data
  file:
    path: "/home/semaphore/{{ site.linux_user }}"
    owner: www-data
    group: www-data
    recurse: true

- name: Adjust Permissions in /var/www/html
  file:
    path: "/home/semaphore/{{ site.linux_user }}"
    owner: www-data
    group: www-data
    recurse: yes
    mode: '0755'
    state: directory

- name: Ensure /home/semaphore is root:www-data  (owner=root, group=www-data)
  file:
    path: /home/semaphore
    owner: root
    group: www-data
    state: directory

# - name: Set /home/semaphore permissions to 0750 (rwx for owner, rx for group)
#   file:
#     path: /home/semaphore
#     mode: '0750'
#     state: directory


- name: Restart Apache after all changes
  service:
    name: apache2
    state: reloaded
    enabled: true


- name: waiting for the 80 port
  ansible.builtin.wait_for:
    host: "{{ site.domain }}"
    port: 80
    state: started        # Espera hasta que el puerto responda
    timeout: 120           # Máx. 1 min

- name: Run the WordPress installation
  ansible.builtin.uri:
    url: "http://{{ site.domain }}/wp-admin/install.php?step=2"
    method: POST
    body: >
      weblog_title={{ site.website_name }}
      &user_name={{ site.wp_admin_user }}
      &admin_password={{ site.wp_admin_pass }}
      &admin_password2={{ site.wp_admin_pass }}
      &admin_email={{ site.wp_admin_email }}
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    status_code: 200
  register: wordpress_install
  ignore_errors: true
